# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30097574c9b85fcbf2860a2773b79e99faf5d6571b53b34e6530553ddb64b88122b9c9b3e99bc971fa659405659b5ebb6c3f1738c1b58e27e645abc52ea903ec

test:
  secret_key_base: fd5f16dd39cb8a98b7c9c9840089d1c7011792950e92aac096d4b49bf5eff2485191df5acb9bab108fb22605241208b2b536aa83f17b619384eb32296812e32c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
